# docker compose build
# docker compose up

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: dockerfile
    image: worker:latest
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      SSH_USERNAME: admin
      SSH_PASSWORD: P@ssw0rd
    deploy:
      replicas: 2
    restart: always


  # rq-dashboard:
  #   image: worker:latest
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: redis
  #   command: rq-dashboard --redis-url redis://redis:6379/0
  #   ports:
  #     - "9181:9181"
    
