# docker compose build
# docker compose up

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: dockerfile
    image: worker:latest
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
